#include "decl.h"

namespace GtNames {
IMPLEMENT_GLOBAL_NAME_1(mvp);
IMPLEMENT_GLOBAL_NAME_1(screenSize)
IMPLEMENT_GLOBAL_NAME_1(invertedMVP)
IMPLEMENT_GLOBAL_NAME_1(eye)
IMPLEMENT_GLOBAL_NAME_1(side)
IMPLEMENT_GLOBAL_NAME_1(up)
IMPLEMENT_GLOBAL_NAME_1(forward)
IMPLEMENT_GLOBAL_NAME_1(view)
IMPLEMENT_GLOBAL_NAME_1(projection)
IMPLEMENT_GLOBAL_NAME_1(rotation)
IMPLEMENT_GLOBAL_NAME_1(viewportProjection)
IMPLEMENT_GLOBAL_NAME_1(camera)
}
