#ifndef ACCELERATIONDECLARATIONS_H
#define ACCELERATIONDECLARATIONS_H

#include "UnitsModule/measurementdeclarations.h"

namespace AccelerationUnits
{
    DECLARE_MEASUREMENT_UNIT(MetersPerSqSec)
    DECLARE_MEASUREMENT_UNIT(MetersPerSqMinute)
    DECLARE_MEASUREMENT_UNIT(MetersPerSqHour)
    DECLARE_MEASUREMENT_UNIT(KilometersPerSqHour)
    DECLARE_MEASUREMENT_UNIT(FeetsPerSqSec)
    DECLARE_MEASUREMENT_UNIT(FeetsPerSqMinute)
    DECLARE_MEASUREMENT_UNIT(FeetsPerSqHour)
    DECLARE_MEASUREMENT_UNIT(USFeetsPerSqSec)
    DECLARE_MEASUREMENT_UNIT(USFeetsPerSqMinute)
    DECLARE_MEASUREMENT_UNIT(USFeetsPerSqHour)
};

DECLARE_MEASUREMENT(Acceleration)

#endif // ACCELERATIONDECLARATIONS_H
