#ifndef AREADECLARATIONS_H
#define AREADECLARATIONS_H

#include "UnitsModule/measurementdeclarations.h"

namespace AreaUnits
{
    DECLARE_MEASUREMENT_UNIT(SqMeters)
    DECLARE_MEASUREMENT_UNIT(SqCentimeters)
    DECLARE_MEASUREMENT_UNIT(SqMilimeters)
    DECLARE_MEASUREMENT_UNIT(SqFeets)
    DECLARE_MEASUREMENT_UNIT(SqUSFeets)
    DECLARE_MEASUREMENT_UNIT(SqInches)
};

DECLARE_MEASUREMENT(Area)

#endif // AREADECLARATIONS_H
