#ifndef DOGLEGDECLARATIONS_H
#define DOGLEGDECLARATIONS_H

#include "UnitsModule/measurementdeclarations.h"

namespace DLSUnits
{
    DECLARE_MEASUREMENT_UNIT(Rad100Feet)
    DECLARE_MEASUREMENT_UNIT(RadMeter)
    DECLARE_MEASUREMENT_UNIT(Rad30Meter)
    DECLARE_MEASUREMENT_UNIT(Degree100Feet)
    DECLARE_MEASUREMENT_UNIT(Degree100USFeet)
    DECLARE_MEASUREMENT_UNIT(Degree30Meter)
};

DECLARE_MEASUREMENT(DLS)

#endif // DOGLEGDECLARATIONS_H
