#ifndef DOGLEGDECLARATIONS_H
#define DOGLEGDECLARATIONS_H

#include "UnitsModule/measurementdeclarations.h"

namespace DLSUnits
{
    DECLARE_MEASUREMENT_UNIT(RadFeet)
    DECLARE_MEASUREMENT_UNIT(RadMeter)
    DECLARE_MEASUREMENT_UNIT(DegreeFeet)
    DECLARE_MEASUREMENT_UNIT(DegreeUSFeet)
    DECLARE_MEASUREMENT_UNIT(DegreeMeter)
};

DECLARE_MEASUREMENT(MeasurementDLS)

#endif // DOGLEGDECLARATIONS_H
