#ifndef MAGNETICDECLARATIONS_H
#define MAGNETICDECLARATIONS_H

#include "UnitsModule/measurementdeclarations.h"

namespace FieldStrengthUnits
{
    DECLARE_MEASUREMENT_UNIT(Tesla)
    DECLARE_MEASUREMENT_UNIT(NanoTeslas)
    DECLARE_MEASUREMENT_UNIT(MicroTeslas)
    DECLARE_MEASUREMENT_UNIT(Gauss)
    DECLARE_MEASUREMENT_UNIT(WeberPerSquareMeter)
    DECLARE_MEASUREMENT_UNIT(MaxwellPerSquareMeter)
}

DECLARE_MEASUREMENT(MagneticField)

namespace MagneticFluxUnits
{
    DECLARE_MEASUREMENT_UNIT(Weber)
    DECLARE_MEASUREMENT_UNIT(MicroWeber)
    DECLARE_MEASUREMENT_UNIT(NanoWeber)
    DECLARE_MEASUREMENT_UNIT(VoltSecod)
    DECLARE_MEASUREMENT_UNIT(Maxwell)
    DECLARE_MEASUREMENT_UNIT(TeslaSquareMeter)
    DECLARE_MEASUREMENT_UNIT(GaussSquareMeter)
    DECLARE_MEASUREMENT_UNIT(GaussSquareCentimeters)
}
DECLARE_MEASUREMENT(MagneticFlux)
#endif // MAGNETICDECLARATIONS_H
