#ifndef MASSDECLARATIONS_H
#define MASSDECLARATIONS_H

#include "UnitsModule/measurementdeclarations.h"

namespace MassUnits
{
    DECLARE_MEASUREMENT_UNIT(Kilograms)
    DECLARE_MEASUREMENT_UNIT(Grams)
    DECLARE_MEASUREMENT_UNIT(Tonnes)
    DECLARE_MEASUREMENT_UNIT(Pounds)
    DECLARE_MEASUREMENT_UNIT(Kilopounds)
}

DECLARE_MEASUREMENT(Mass)

#endif // MASSDECLARATIONS_H
