#ifndef TIMEDECLARATIONS_H
#define TIMEDECLARATIONS_H

#include "UnitsModule/measurementdeclarations.h"

namespace TimeUnits
{
    DECLARE_MEASUREMENT_UNIT(MSeconds)
    DECLARE_MEASUREMENT_UNIT(Seconds)
    DECLARE_MEASUREMENT_UNIT(Minutes)
    DECLARE_MEASUREMENT_UNIT(Hours)
    DECLARE_MEASUREMENT_UNIT(Day)
    DECLARE_MEASUREMENT_UNIT(Months)
    DECLARE_MEASUREMENT_UNIT(Years)
};

DECLARE_MEASUREMENT(Time)
DECLARE_MEASUREMENT(SSTime)

#endif // TIMEDECLARATIONS_H
