#ifndef WEIGHTPERLENGTHDECLARATIONS_H
#define WEIGHTPERLENGTHDECLARATIONS_H

#include "UnitsModule/measurementdeclarations.h"

namespace WeightPerLengthUnits
{
    DECLARE_MEASUREMENT_UNIT(NewtonPerMeter)
    DECLARE_MEASUREMENT_UNIT(KilogramPerMeter)
    DECLARE_MEASUREMENT_UNIT(PoundPerFoot)
    DECLARE_MEASUREMENT_UNIT(PoundPerInch)
}

DECLARE_MEASUREMENT(WeightPerLength)

#endif // WEIGHTPERLENGTHDECLARATIONS_H
